import type { FeaturedHall } from "@/types/hall";

/** Demo halls used when featured API is unavailable (design/dev fallback). */
export const FEATURED_HALLS_FALLBACK: FeaturedHall[] = [
  {
    id: "1",
    name: "قاعة رويال",
    imageUrl: "/halls/featured-lotus.webp",
    priceLabel: "1,500 / يوم",
    rating: 4.9,
    reviewCount: 42,
    location: "غزة",
    capacity: 500,
    capacityMax: 800,
    tags: ["مكيفة", "حديقة خارجية", "مولد كهرباء"],
    region: "gaza",
    bookedPeriodsSummary: "15 August · الفترة الأولى",
    availabilityDays: [
      {
        dateLabel: "15 August",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "booked" },
          { label: "الفترة الثانية", time: "4:00 م – 8:00 م", status: "available" },
        ],
      },
      {
        dateLabel: "16 August",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "available" },
          { label: "الفترة الثانية", time: "4:00 م – 8:00 م", status: "available" },
        ],
      },
    ],
  },
  {
    id: "2",
    name: "قاعة الأندلس",
    imageUrl: "/halls/featured-02.webp",
    priceLabel: "980 / يوم",
    rating: 4.7,
    reviewCount: 28,
    location: "شمال غزة",
    capacity: 350,
    tags: ["كلاسيك", "إضاءة مميزة"],
    region: "north",
    bookedPeriodsSummary: null,
    availabilityDays: [
      {
        dateLabel: "15 August",
        periods: [
          { label: "الفترة الأولى", time: "11:00 ص – 2:00 م", status: "available" },
          { label: "الفترة الثانية", time: "5:00 م – 9:00 م", status: "available" },
        ],
      },
    ],
  },
  {
    id: "3",
    name: "قاعة النخيل الذهبية",
    imageUrl: "/halls/featured-03.webp",
    priceLabel: "1,100 / يوم",
    rating: 4.8,
    reviewCount: 36,
    location: "وسط غزة",
    capacity: 420,
    tags: ["مفتوحة", "حفلة خطوبة"],
    region: "middle",
    bookedPeriodsSummary: "16 August · الفترة الثانية",
    availabilityDays: [
      {
        dateLabel: "16 August",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "available" },
          { label: "الفترة الثانية", time: "4:00 م – 8:00 م", status: "booked" },
        ],
      },
    ],
  },
  {
    id: "4",
    name: "قاعة الياسمين",
    imageUrl: "/halls/featured-04.webp",
    priceLabel: "870 / يوم",
    rating: 4.6,
    reviewCount: 19,
    location: "جنوب غزة",
    capacity: 280,
    tags: ["مكيفة", "ديكور حديث"],
    region: "south",
    bookedPeriodsSummary: null,
    availabilityDays: [
      {
        dateLabel: "17 August",
        periods: [
          { label: "الفترة الأولى", time: "1:00 م – 4:00 م", status: "available" },
          { label: "الفترة الثانية", time: "5:00 م – 10:00 م", status: "available" },
        ],
      },
    ],
  },
  {
    id: "5",
    name: "قاعة القمر الفضي",
    imageUrl: "/halls/featured-05.webp",
    priceLabel: "1,400 / يوم",
    rating: 5,
    reviewCount: 51,
    location: "غزة - تل الهوا",
    capacity: 600,
    tags: ["VIP", "موقف سيارات"],
    region: "gaza",
    bookedPeriodsSummary: "18 August · الفترة الأولى",
    availabilityDays: [
      {
        dateLabel: "18 August",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "booked" },
          { label: "الفترة الثانية", time: "4:00 م – 8:00 م", status: "booked" },
        ],
      },
    ],
  },
  {
    id: "6",
    name: "قاعة الريحان",
    imageUrl: "/halls/featured-06.webp",
    priceLabel: "750 / يوم",
    rating: 4.5,
    reviewCount: 14,
    location: "رفح",
    capacity: 220,
    tags: ["اقتصادية", "مكيفة"],
    region: "south",
    bookedPeriodsSummary: null,
    availabilityDays: [
      {
        dateLabel: "19 August",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "available" },
          { label: "الفترة الثانية", time: "4:00 م – 8:00 م", status: "available" },
        ],
      },
    ],
  },
  {
    id: "7",
    name: "قاعة الزيتون",
    imageUrl: "/halls/featured-02.webp",
    priceLabel: "920 / يوم",
    rating: 4.6,
    reviewCount: 22,
    location: "جباليا",
    capacity: 300,
    tags: ["مفتوحة", "حديقة"],
    region: "north",
    bookedPeriodsSummary: null,
    availabilityDays: [
      {
        dateLabel: "20 August",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "available" },
          { label: "الفترة الثانية", time: "5:00 م – 9:00 م", status: "available" },
        ],
      },
    ],
  },
  {
    id: "8",
    name: "قاعة الفردوس",
    imageUrl: "/halls/featured-04.webp",
    priceLabel: "1,250 / يوم",
    rating: 4.8,
    reviewCount: 31,
    location: "تل الهوا",
    capacity: 480,
    tags: ["مكيفة", "VIP"],
    region: "gaza",
    bookedPeriodsSummary: "21 August · الفترة الأولى",
    availabilityDays: [
      {
        dateLabel: "21 August",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "booked" },
          { label: "الفترة الثانية", time: "4:00 م – 8:00 م", status: "available" },
        ],
      },
    ],
  },
  {
    id: "9",
    name: "قاعة السوسن",
    imageUrl: "/halls/featured-05.webp",
    priceLabel: "830 / يوم",
    rating: 4.4,
    reviewCount: 17,
    location: "خان يونس",
    capacity: 260,
    tags: ["حفلة خطوبة", "مكيفة"],
    region: "south",
    bookedPeriodsSummary: null,
    availabilityDays: [
      {
        dateLabel: "22 August",
        periods: [
          { label: "الفترة الأولى", time: "1:00 م – 4:00 م", status: "available" },
          { label: "الفترة الثانية", time: "6:00 م – 10:00 م", status: "available" },
        ],
      },
    ],
  },
  {
    id: "10",
    name: "قاعة النور",
    imageUrl: "/halls/featured-03.webp",
    priceLabel: "1,050 / يوم",
    rating: 4.7,
    reviewCount: 25,
    location: "النصيرات",
    capacity: 380,
    tags: ["مفتوحة", "إضاءة مميزة"],
    region: "middle",
    bookedPeriodsSummary: "23 August · الفترة الثانية",
    availabilityDays: [
      {
        dateLabel: "23 August",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "available" },
          { label: "الفترة الثانية", time: "4:00 م – 8:00 م", status: "booked" },
        ],
      },
    ],
  },
  {
    id: "11",
    name: "قاعة الكرامة",
    imageUrl: "/halls/featured-lotus.webp",
    priceLabel: "990 / يوم",
    rating: 4.5,
    reviewCount: 20,
    location: "الشجاعية",
    capacity: 340,
    tags: ["مكيفة", "موقف سيارات"],
    region: "gaza",
    bookedPeriodsSummary: null,
    availabilityDays: [
      {
        dateLabel: "24 August",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "available" },
          { label: "الفترة الثانية", time: "4:00 م – 8:00 م", status: "available" },
        ],
      },
    ],
  },
  {
    id: "12",
    name: "قاعة الأمل",
    imageUrl: "/halls/featured-06.webp",
    priceLabel: "1,180 / يوم",
    rating: 4.9,
    reviewCount: 40,
    location: "بيت لاهيا",
    capacity: 450,
    tags: ["VIP", "حفلة زفاف"],
    region: "north",
    bookedPeriodsSummary: "25 August · الفترة الأولى",
    availabilityDays: [
      {
        dateLabel: "25 August",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "booked" },
          { label: "الفترة الثانية", time: "5:00 م – 9:00 م", status: "available" },
        ],
      },
    ],
  },
  {
    id: "13",
    name: "قاعة الياسمين البيضاء",
    imageUrl: "/halls/featured-04.webp",
    priceLabel: "860 / يوم",
    rating: 4.3,
    reviewCount: 12,
    location: "دير البلح",
    capacity: 240,
    tags: ["مكيفة", "اقتصادية"],
    region: "middle",
    bookedPeriodsSummary: null,
    availabilityDays: [
      {
        dateLabel: "26 August",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "available" },
          { label: "الفترة الثانية", time: "4:00 م – 8:00 م", status: "available" },
        ],
      },
    ],
  },
  {
    id: "14",
    name: "قاعة الشام",
    imageUrl: "/halls/featured-02.webp",
    priceLabel: "1,320 / يوم",
    rating: 4.8,
    reviewCount: 29,
    location: "الرمال",
    capacity: 520,
    tags: ["VIP", "مكيفة"],
    region: "gaza",
    bookedPeriodsSummary: "27 August · الفترة الثانية",
    availabilityDays: [
      {
        dateLabel: "27 August",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "available" },
          { label: "الفترة الثانية", time: "5:00 م – 9:00 م", status: "booked" },
        ],
      },
    ],
  },
  {
    id: "15",
    name: "قاعة البحر",
    imageUrl: "/halls/featured-03.webp",
    priceLabel: "1,080 / يوم",
    rating: 4.6,
    reviewCount: 21,
    location: "الكورنيش",
    capacity: 360,
    tags: ["مفتوحة", "إطلالة"],
    region: "gaza",
    bookedPeriodsSummary: null,
    availabilityDays: [
      {
        dateLabel: "28 August",
        periods: [
          { label: "الفترة الأولى", time: "1:00 م – 4:00 م", status: "available" },
          { label: "الفترة الثانية", time: "6:00 م – 10:00 م", status: "available" },
        ],
      },
    ],
  },
  {
    id: "16",
    name: "قاعة الوردة",
    imageUrl: "/halls/featured-05.webp",
    priceLabel: "940 / يوم",
    rating: 4.4,
    reviewCount: 16,
    location: "بيت حانون",
    capacity: 280,
    tags: ["حفلة خطوبة", "حديقة"],
    region: "north",
    bookedPeriodsSummary: null,
    availabilityDays: [
      {
        dateLabel: "29 August",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "available" },
          { label: "الفترة الثانية", time: "4:00 م – 8:00 م", status: "available" },
        ],
      },
    ],
  },
  {
    id: "17",
    name: "قاعة الماس",
    imageUrl: "/halls/featured-lotus.webp",
    priceLabel: "1,450 / يوم",
    rating: 5,
    reviewCount: 44,
    location: "الشيخ رضوان",
    capacity: 550,
    tags: ["VIP", "حفلات كبرى"],
    region: "gaza",
    bookedPeriodsSummary: "30 August · الفترة الأولى",
    availabilityDays: [
      {
        dateLabel: "30 August",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "booked" },
          { label: "الفترة الثانية", time: "4:00 م – 8:00 م", status: "available" },
        ],
      },
    ],
  },
  {
    id: "18",
    name: "قاعة السلام",
    imageUrl: "/halls/featured-06.webp",
    priceLabel: "780 / يوم",
    rating: 4.2,
    reviewCount: 11,
    location: "عبسان",
    capacity: 200,
    tags: ["اقتصادية", "مكيفة"],
    region: "south",
    bookedPeriodsSummary: null,
    availabilityDays: [
      {
        dateLabel: "31 August",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "available" },
          { label: "الفترة الثانية", time: "4:00 م – 8:00 م", status: "available" },
        ],
      },
    ],
  },
  {
    id: "19",
    name: "قاعة اللؤلؤة",
    imageUrl: "/halls/featured-lotus.webp",
    priceLabel: "1,220 / يوم",
    rating: 4.7,
    reviewCount: 27,
    location: "الزيتون",
    capacity: 400,
    tags: ["مكيفة", "ديكور فاخر"],
    region: "gaza",
    bookedPeriodsSummary: "1 September · الفترة الأولى",
    availabilityDays: [
      {
        dateLabel: "1 September",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "booked" },
          { label: "الفترة الثانية", time: "4:00 م – 8:00 م", status: "available" },
        ],
      },
    ],
  },
  {
    id: "20",
    name: "قاعة السنابل",
    imageUrl: "/halls/featured-02.webp",
    priceLabel: "890 / يوم",
    rating: 4.5,
    reviewCount: 18,
    location: "بيت حانون",
    capacity: 270,
    tags: ["مفتوحة", "حديقة"],
    region: "north",
    bookedPeriodsSummary: null,
    availabilityDays: [
      {
        dateLabel: "2 September",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "available" },
          { label: "الفترة الثانية", time: "5:00 م – 9:00 م", status: "available" },
        ],
      },
    ],
  },
  {
    id: "21",
    name: "قاعة الواحة",
    imageUrl: "/halls/featured-03.webp",
    priceLabel: "1,160 / يوم",
    rating: 4.8,
    reviewCount: 33,
    location: "المغازي",
    capacity: 410,
    tags: ["VIP", "إضاءة مميزة"],
    region: "middle",
    bookedPeriodsSummary: "3 September · الفترة الثانية",
    availabilityDays: [
      {
        dateLabel: "3 September",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "available" },
          { label: "الفترة الثانية", time: "4:00 م – 8:00 م", status: "booked" },
        ],
      },
    ],
  },
  {
    id: "22",
    name: "قاعة الكرمل",
    imageUrl: "/halls/featured-04.webp",
    priceLabel: "970 / يوم",
    rating: 4.4,
    reviewCount: 15,
    location: "خان يونس",
    capacity: 310,
    tags: ["مكيفة", "حفلة خطوبة"],
    region: "south",
    bookedPeriodsSummary: null,
    availabilityDays: [
      {
        dateLabel: "4 September",
        periods: [
          { label: "الفترة الأولى", time: "1:00 م – 4:00 م", status: "available" },
          { label: "الفترة الثانية", time: "6:00 م – 10:00 م", status: "available" },
        ],
      },
    ],
  },
  {
    id: "23",
    name: "قاعة البستان",
    imageUrl: "/halls/featured-05.webp",
    priceLabel: "1,350 / يوم",
    rating: 4.9,
    reviewCount: 38,
    location: "جباليا البلد",
    capacity: 490,
    tags: ["حديقة خارجية", "VIP"],
    region: "north",
    bookedPeriodsSummary: "5 September · الفترة الأولى",
    availabilityDays: [
      {
        dateLabel: "5 September",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "booked" },
          { label: "الفترة الثانية", time: "5:00 م – 9:00 م", status: "available" },
        ],
      },
    ],
  },
  {
    id: "24",
    name: "قاعة الفيروز",
    imageUrl: "/halls/featured-06.webp",
    priceLabel: "1,020 / يوم",
    rating: 4.6,
    reviewCount: 23,
    location: "رفح الغربية",
    capacity: 330,
    tags: ["مكيفة", "موقف سيارات"],
    region: "south",
    bookedPeriodsSummary: null,
    availabilityDays: [
      {
        dateLabel: "6 September",
        periods: [
          { label: "الفترة الأولى", time: "12:00 م – 3:00 م", status: "available" },
          { label: "الفترة الثانية", time: "4:00 م – 8:00 م", status: "available" },
        ],
      },
    ],
  },
];
